package com.artverse.provenance;

import com.artverse.artwork.Artwork;
import com.artverse.artwork.ArtworkRepository;
import com.artverse.common.ApiException;
import com.artverse.marketplace.ArtworkOwnership;
import com.artverse.marketplace.ArtworkOwnershipRepository;
import com.artverse.marketplace.Order;
import com.artverse.marketplace.OrderRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class ProvenanceService {
    private final ArtworkRepository artworks;
    private final ArtworkOwnershipRepository ownership;
    private final OrderRepository orders;

    public ProvenanceDtos.Response get(UUID artworkId) {
        Artwork artwork = artworks.findById(artworkId).orElseThrow(() ->
                ApiException.notFound("ARTWORK_NOT_FOUND", "Artwork not found"));
        ArtworkOwnership current = ownership.findFirstByArtworkIdOrderByAcquiredAtDesc(artworkId).orElse(null);
        List<ProvenanceDtos.Transaction> transactions = orders.findByArtworkIdOrderByCreatedAtAsc(artworkId).stream()
                .map(this::transaction)
                .toList();
        String certificate = "AV-" + artworkId.toString().replace("-", "").substring(0, 12).toUpperCase();
        Instant issuedAt = current == null ? Instant.now() : current.getAcquiredAt();
        return new ProvenanceDtos.Response(artwork.getId(), artwork.getTitle(), artwork.getArtistId(),
                current == null ? artwork.getArtistId() : current.getOwnerId(), certificate, issuedAt, transactions);
    }

    public String certificateHtml(UUID artworkId) {
        ProvenanceDtos.Response p = get(artworkId);
        StringBuilder html = new StringBuilder("<!doctype html><html><head><meta charset='UTF-8'><title>ArtVerse Provenance Certificate</title>")
                .append("<style>body{font-family:Georgia,serif;background:#f3ead8;color:#211d18;padding:60px}.sheet{max-width:800px;margin:auto;border:1px solid #8b7355;padding:55px;background:#f8f0df}h1{text-align:center;font-size:34px}.meta{text-transform:uppercase;letter-spacing:3px;font:11px Arial;color:#6d7058}.line{border-top:1px solid #b9a98e;margin:30px 0}.row{margin:16px 0}small{color:#6d6254}</style></head><body><div class='sheet'>")
                .append("<div class='meta'>ARTVERSE · CERTIFICATE OF PROVENANCE</div><h1>").append(escape(p.title())).append("</h1>")
                .append("<div class='line'></div><div class='row'><b>Certificate:</b> ").append(p.certificateNumber()).append("</div>")
                .append("<div class='row'><b>Artist ID:</b> ").append(p.artistId()).append("</div>")
                .append("<div class='row'><b>Current Owner ID:</b> ").append(p.currentOwnerId()).append("</div>")
                .append("<div class='row'><b>Issued:</b> ").append(p.issuedAt()).append("</div><div class='line'></div>")
                .append("<h2>Transaction History</h2>");
        if (p.transactions().isEmpty()) html.append("<p>No recorded sales or auction settlements. Original creator ownership is recorded.</p>");
        else for (var t : p.transactions()) html.append("<div class='row'><b>").append(t.status()).append("</b> · ").append(t.amount()).append(" ").append(escape(t.currency())).append(" · ").append(t.createdAt()).append("</div>");
        html.append("<div class='line'></div><small>Digital provenance record generated by ArtVerse. This document records platform transactions and is not a legal appraisal or independent authenticity guarantee.</small></div></body></html>");
        return html.toString();
    }

    private ProvenanceDtos.Transaction transaction(Order o) {
        return new ProvenanceDtos.Transaction(o.getId(), o.getSellerId(), o.getBuyerId(), o.getAuctionId(),
                o.getAmount(), o.getCurrency(), o.getStatus().name(), o.getCreatedAt(), o.getPaymentReference());
    }

    private String escape(String value) {
        if (value == null) return "";
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "&#39;");
    }
}
