import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, extractErrorMessage } from '@/lib/api'

type Listing = { id:string; artworkId:string; sellerId:string; sellerName:string; title:string; imageUrl?:string; category:string; style?:string; medium?:string; price:number; currency:string; status:string }
type Page<T> = { content?:T[]; totalPages?:number; number?:number }
type Order = { id:string; buyerId:string; sellerId?:string; artworkId:string; auctionId?:string; amount:number; currency:string; status:string; paymentReference?:string; createdAt:string }

export function MarketplacePage(){
 const [listings,setListings]=useState<Listing[]>([]),[orders,setOrders]=useState<Order[]>([]),[q,setQ]=useState(''),[category,setCategory]=useState(''),[style,setStyle]=useState(''),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[paying,setPaying]=useState('')
 async function load(){setLoading(true);setError('');try{const [l,o]=await Promise.all([api.get<Page<Listing>>('/marketplace/listings',{params:{page:0,size:24,q:q||undefined,category:category||undefined,style:style||undefined,minPrice:minPrice||undefined,maxPrice:maxPrice||undefined}}),api.get<Page<Order>>('/marketplace/orders/me',{params:{page:0,size:20}})]);setListings(l.data.content??[]);setOrders(o.data.content??[])}catch(e){setError(extractErrorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function buy(id:string){setMessage('');setError('');try{const r=await api.post<Order>(`/marketplace/orders/${id}`);setMessage(`Order ${r.data.id.slice(0,8)} created. Complete payment in your ledger.`);await load()}catch(e){setError(extractErrorMessage(e))}}
 async function pay(order:Order){setPaying(order.id);setError('');try{await api.post(`/marketplace/orders/${order.id}/pay`,{paymentReference:`ARTVERSE-DEMO-${Date.now()}`});setMessage('Payment recorded and ownership transferred successfully.');await load()}catch(e){setError(extractErrorMessage(e))}finally{setPaying('')}}
 const pending=orders.filter(o=>o.status==='PENDING')
 return <main className="mx-auto max-w-7xl px-6 py-16 sm:px-10">
  <header className="border-b border-ink/15 pb-10"><p className="label-meta">The ARTVERSE market</p><h1 className="mt-3 max-w-4xl font-serif text-5xl sm:text-7xl">Works worth living with.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-ink/60">A considered catalogue of original works, offered directly by the artists who made them.</p></header>
  <section className="mt-8 border border-ink/10 bg-paper p-5 shadow-[0_12px_40px_rgba(29,27,24,.05)]"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5"><input className="field lg:col-span-2" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void load()}} placeholder="Search title, artist, medium…"/><input className="field" value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category"/><input className="field" value={style} onChange={e=>setStyle(e.target.value)} placeholder="Style"/><div className="flex gap-3"><input className="field min-w-0" type="number" min="0" value={minPrice} onChange={e=>setMinPrice(e.target.value)} placeholder="Min ₹"/><input className="field min-w-0" type="number" min="0" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Max ₹"/></div></div><button onClick={()=>void load()} className="btn-outline mt-5">Search market</button></section>
  {message&&<p className="mt-6 border border-olive/20 bg-olive/[.04] p-4 text-sm text-olive">{message}</p>}{error&&<p className="mt-6 border border-oxblood/20 bg-oxblood/[.03] p-4 text-sm text-oxblood">{error}</p>}
  {pending.length>0&&<section className="mt-10 border border-oxblood/20 bg-oxblood/[.025] p-6"><p className="label-meta">Your ledger</p><h2 className="mt-2 font-serif text-3xl">Orders awaiting payment</h2><div className="mt-5 divide-y divide-ink/10">{pending.map(o=><article key={o.id} className="flex flex-col justify-between gap-4 py-5 sm:flex-row sm:items-center"><div><p className="font-serif text-2xl">{o.currency} {o.amount.toLocaleString()}</p><p className="mt-1 text-xs text-ink/40">Order {o.id.slice(0,8)} · {new Date(o.createdAt).toLocaleDateString()}</p></div><div className="flex gap-3"><Link to={`/artworks/${o.artworkId}`} className="btn-outline">View work</Link><button disabled={paying===o.id} onClick={()=>void pay(o)} className="bg-oxblood px-5 py-3 text-[10px] uppercase tracking-wider text-paper disabled:opacity-40">{paying===o.id?'Processing…':'Complete payment'}</button></div></article>)}</div></section>}
  <section className="mt-12"><div className="flex items-end justify-between border-b border-ink/15 pb-4"><div><p className="label-meta">Available now</p><h2 className="mt-2 font-serif text-3xl">The catalogue</h2></div><span className="text-xs text-ink/40">{listings.length} works shown</span></div>
   {loading?<p className="py-20 text-center text-sm text-ink/45">Opening the market ledger…</p>:listings.length===0?<div className="border border-dashed border-ink/20 py-20 text-center"><p className="label-meta">Quiet shelves</p><p className="mt-2 font-serif text-2xl">No works match these terms.</p></div>:<div className="mt-7 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{listings.map(l=><article key={l.id} className="museum-card overflow-hidden"><Link to={`/artworks/${l.artworkId}`} className="block aspect-[4/5] overflow-hidden bg-ivory">{l.imageUrl?<img src={l.imageUrl} alt={l.title} className="h-full w-full object-cover transition duration-700 hover:scale-[1.03]"/>:<div className="flex h-full items-center justify-center font-serif text-3xl text-ink/15">ARTVERSE</div>}</Link><div className="p-6"><p className="label-meta">{l.category}{l.style?` · ${l.style}`:''}</p><h3 className="mt-2 font-serif text-2xl">{l.title}</h3><p className="mt-1 text-sm text-ink/50">by {l.sellerName}</p>{l.medium&&<p className="mt-3 text-xs italic text-ink/45">{l.medium}</p>}<div className="mt-6 flex items-end justify-between border-t border-ink/10 pt-5"><div><p className="text-[10px] uppercase tracking-wider text-ink/40">Asking price</p><p className="mt-1 font-serif text-2xl">{l.currency} {l.price.toLocaleString()}</p></div><button onClick={()=>void buy(l.id)} className="bg-oxblood px-4 py-3 text-[10px] uppercase tracking-wider text-paper hover:bg-ink">Acquire</button></div></div></article>)}</div>}
  </section>
  <section className="mt-16 border-t border-ink/10 pt-10"><p className="label-meta">Purchase history</p><h2 className="mt-2 font-serif text-3xl">Your ledger</h2>{orders.length===0?<p className="mt-5 text-sm text-ink/45">Your purchases will appear here.</p>:<div className="mt-5 divide-y divide-ink/10 border-y border-ink/10">{orders.map(o=><article key={o.id} className="flex items-center justify-between gap-4 px-2 py-5"><div><p className="font-serif text-xl">{o.currency} {o.amount.toLocaleString()}</p><p className="mt-1 text-xs text-ink/40">{new Date(o.createdAt).toLocaleDateString()}</p></div><span className={`text-[10px] uppercase tracking-[.14em] ${o.status==='PAID'?'text-olive':'text-oxblood'}`}>{o.status}</span></article>)}</div>}</section>
 </main>
}
