import { ChangeEvent, DragEvent, useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, extractErrorMessage } from '@/lib/api'
import type { Artwork } from '@/types/artwork'

type Page<T> = { content?: T[] }
type MediaResponse = { id:string; artworkId:string; originalName:string; url:string; provider:string; contentType:string; fileSize:number; checksum:string; createdAt:string }
const MAX_BYTES = 10 * 1024 * 1024
const TYPES = ['image/jpeg','image/png','image/webp']

export function StudioMediaPage(){
 const [works,setWorks]=useState<Artwork[]>([]),[artworkId,setArtworkId]=useState(''),[file,setFile]=useState<File|null>(null),[dragging,setDragging]=useState(false),[uploading,setUploading]=useState(false),[progress,setProgress]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState(''),[uploaded,setUploaded]=useState<MediaResponse|null>(null)
 useEffect(()=>{api.get<Page<Artwork>>('/artworks/mine',{params:{page:0,size:50}}).then(r=>setWorks(r.data.content??[])).catch(e=>setError(extractErrorMessage(e)))},[])
 const selected=useMemo(()=>works.find(w=>w.id===artworkId),[works,artworkId])
 const preview=useMemo(()=>file?URL.createObjectURL(file):'', [file])
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
 function choose(candidate:File|null){setError('');setMessage('');setUploaded(null);if(!candidate)return;if(!TYPES.includes(candidate.type)){setError('Only JPEG, PNG, and WebP images are supported.');return}if(candidate.size>MAX_BYTES){setError('Image must be 10 MB or smaller.');return}setFile(candidate)}
 function onInput(e:ChangeEvent<HTMLInputElement>){choose(e.target.files?.[0]??null)}
 function onDrop(e:DragEvent<HTMLDivElement>){e.preventDefault();setDragging(false);choose(e.dataTransfer.files?.[0]??null)}
 async function upload(){if(!artworkId){setError('Choose an artwork first.');return}if(!file){setError('Choose an image first.');return}setUploading(true);setProgress(0);setError('');setMessage('Preserving your image in the collection…');try{const form=new FormData();form.append('file',file);const r=await api.post<MediaResponse>(`/media/artworks/${artworkId}`,form,{onUploadProgress:e=>{if(e.total)setProgress(Math.round((e.loaded/e.total)*100))}});setUploaded(r.data);setMessage(`Image attached to “${selected?.title??'the artwork'}”.`);setFile(null);setProgress(100);const refreshed=await api.get<Page<Artwork>>('/artworks/mine',{params:{page:0,size:50}});setWorks(refreshed.data.content??[])}catch(e){setError(extractErrorMessage(e,'The image could not be uploaded. Please try again.'));setProgress(0)}finally{setUploading(false)}}
 const displayUrl=(url:string)=>{try{return new URL(url,import.meta.env.VITE_API_URL??'http://localhost:8080/api/v1').toString()}catch{return url}}
 return <main className="mx-auto max-w-5xl px-6 py-14 sm:px-10"><header className="border-b border-ink/15 pb-9"><Link to="/studio" className="label-meta hover:text-oxblood">← Artist studio</Link><h1 className="mt-4 font-serif text-5xl sm:text-6xl">The image room.</h1><p className="mt-4 max-w-2xl text-ink/60">Prepare a high-quality image for an artwork before it enters the gallery. Files are checked before they leave your hands.</p></header>
 {(message||error)&&<p className={`mt-6 border p-4 text-sm ${error?'border-oxblood/20 text-oxblood':'border-olive/20 text-olive'}`}>{error||message}</p>}
 <section className="mt-10 grid gap-10 md:grid-cols-[1fr_1.25fr]">
  <div><p className="label-meta">1 · Select the work</p><select value={artworkId} onChange={e=>setArtworkId(e.target.value)} className="field mt-3"><option value="">Choose an artwork…</option>{works.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select>{selected&&<div className="mt-5 border border-ink/10 p-5"><p className="label-meta">Selected record</p><h2 className="mt-2 font-serif text-2xl">{selected.title}</h2><p className="mt-2 text-sm text-ink/50">{selected.category} · {selected.style||'Unspecified style'} · {selected.medium||'Unspecified medium'}</p>{selected.imageUrl&&<img src={displayUrl(selected.imageUrl)} alt={selected.title} className="mt-5 aspect-[4/3] w-full object-cover"/>}</div>}</div>
  <div><p className="label-meta">2 · Prepare the image</p><div onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={onDrop} className={`mt-3 border-2 border-dashed p-6 text-center transition ${dragging?'border-oxblood bg-oxblood/5':'border-ink/20'}`}><input id="art-file" type="file" accept="image/jpeg,image/png,image/webp" onChange={onInput} className="sr-only"/><label htmlFor="art-file" className="block cursor-pointer"><div className="mx-auto flex aspect-[4/3] max-w-lg items-center justify-center overflow-hidden bg-ivory">{preview?<img src={preview} alt="Selected artwork preview" className="h-full w-full object-contain"/>:<div><p className="font-serif text-3xl text-ink/30">Drop the image here</p><p className="mt-2 text-sm text-ink/45">or click to browse</p></div>}</div></label><p className="mt-5 text-[10px] uppercase tracking-[0.14em] text-ink/40">JPEG · PNG · WebP · maximum 10 MB</p>{file&&<div className="mt-4 text-sm text-ink/65">{file.name} · {(file.size/1024/1024).toFixed(2)} MB</div>}</div>
  <button onClick={()=>void upload()} disabled={uploading||!file||!artworkId} className="mt-5 w-full bg-oxblood px-8 py-4 text-sm uppercase tracking-widest text-paper disabled:cursor-not-allowed disabled:opacity-40">{uploading?`Uploading ${progress}%…`:'Attach image to artwork'}</button>{uploading&&<div className="mt-3 h-1 bg-ink/10"><div className="h-1 bg-oxblood transition-all" style={{width:`${progress}%`}}/></div>}
  </div>
 </section>
 {uploaded&&<section className="mt-12 border-t border-ink/10 pt-10"><p className="label-meta">Preservation record</p><div className="mt-4 grid gap-6 border-y border-ink/10 p-5 sm:grid-cols-[180px_1fr]"><img src={displayUrl(uploaded.url)} alt={uploaded.originalName} className="aspect-square w-full object-cover"/><div><h2 className="font-serif text-2xl">Image attached successfully.</h2><dl className="mt-5 grid gap-3 text-sm"><div><dt className="label-meta">Storage</dt><dd className="mt-1">{uploaded.provider}</dd></div><div><dt className="label-meta">Format</dt><dd className="mt-1">{uploaded.contentType}</dd></div><div><dt className="label-meta">Size</dt><dd className="mt-1">{(uploaded.fileSize/1024/1024).toFixed(2)} MB</dd></div><div><dt className="label-meta">Checksum</dt><dd className="mt-1 break-all font-mono text-xs text-ink/55">{uploaded.checksum}</dd></div></dl></div></div></section>}
 </main>
}