import { FormEvent, useEffect, useMemo, useState, type ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { api, extractErrorMessage } from '@/lib/api'
import { createArtwork } from '@/lib/artworks'
import type { Artwork } from '@/types/artwork'

type Page<T> = { content?: T[] }
type Listing = { id:string; artworkId:string; price:number; currency:string; status:string; createdAt:string }
type Auction = { id:string; artworkId:string; startingPrice:number; currentPrice:number; minimumIncrement:number; currency:string; startsAt:string; endsAt:string; status:string; winnerId?:string }
type Sale = { id:string; artworkId:string; amount:number; currency:string; status:string; auctionId?:string; buyerId?:string; createdAt:string }

export function StudioPage(){
 const [works,setWorks]=useState<Artwork[]>([]),[listings,setListings]=useState<Listing[]>([]),[auctions,setAuctions]=useState<Auction[]>([]),[sales,setSales]=useState<Sale[]>([])
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(''),[action,setAction]=useState('')
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[imageUrl,setImageUrl]=useState(''),[category,setCategory]=useState('Painting'),[medium,setMedium]=useState(''),[style,setStyle]=useState(''),[year,setYear]=useState(''),[price,setPrice]=useState('')
 async function load(){setLoading(true);setError('');try{const [w,l,a,s]=await Promise.all([api.get<Page<Artwork>>('/artworks/mine',{params:{page:0,size:50}}),api.get<Page<Listing>>('/marketplace/listings/mine',{params:{page:0,size:50}}),api.get<Page<Auction>>('/auctions/mine',{params:{page:0,size:50}}),api.get<Page<Sale>>('/marketplace/sales/me',{params:{page:0,size:50}})]);setWorks(w.data.content??[]);setListings(l.data.content??[]);setAuctions(a.data.content??[]);setSales(s.data.content??[])}catch(e){setError(extractErrorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function submit(e:FormEvent){e.preventDefault();setMessage('Saving work...');setError('');try{const a=await createArtwork({title,description,imageUrl,category,medium,style,yearCreated:year?Number(year):undefined,price:price?Number(price):undefined,currency:'INR',status:'PUBLISHED'});setWorks(w=>[a,...w]);setTitle('');setDescription('');setImageUrl('');setMedium('');setStyle('');setYear('');setPrice('');setMessage('Work added to your archive.')}catch(e){setError(extractErrorMessage(e));setMessage('')}}
 async function remove(id:string){if(!window.confirm('Remove this work from the archive?'))return;setAction(id);setError('');try{await api.delete(`/artworks/${id}`);setWorks(w=>w.filter(a=>a.id!==id));setMessage('Work removed.')}catch(e){setError(extractErrorMessage(e))}finally{setAction('')}}
 async function market(a:Artwork){const value=window.prompt('Listing price (INR)',String(a.price??''));const amount=Number(value);if(!value||!Number.isFinite(amount)||amount<=0)return;setAction(`market-${a.id}`);try{await api.post(`/marketplace/listings/${a.id}`,{price:amount,currency:'INR'});setMessage('Work released to the private market.');await load()}catch(e){setError(extractErrorMessage(e))}finally{setAction('')}}
 async function auction(a:Artwork){const start=Number(window.prompt('Starting price (INR)',String(a.price??'')));if(!Number.isFinite(start)||start<=0)return;const increment=Number(window.prompt('Minimum bid increment (INR)','500'));if(!Number.isFinite(increment)||increment<=0)return;setAction(`auction-${a.id}`);try{await api.post(`/auctions/artworks/${a.id}`,{startingPrice:start,minimumIncrement:increment,currency:'INR',startsAt:new Date(Date.now()+60000).toISOString(),endsAt:new Date(Date.now()+86400000).toISOString()});setMessage('Auction created. It opens in one minute and runs for 24 hours.');await load()}catch(e){setError(extractErrorMessage(e))}finally{setAction('')}}
 async function cancelListing(id:string){if(!window.confirm('Cancel this marketplace listing?'))return;setAction(`cancel-${id}`);try{await api.delete(`/marketplace/listings/${id}`);setMessage('Marketplace listing cancelled.');await load()}catch(e){setError(extractErrorMessage(e))}finally{setAction('')}}
 async function closeAuction(id:string){setAction(`close-${id}`);try{await api.post(`/auctions/${id}/close`);setMessage('Auction closed and winner settlement prepared.');await load()}catch(e){setError(extractErrorMessage(e))}finally{setAction('')}}
 const paidSales=useMemo(()=>sales.filter(s=>s.status==='PAID'),[sales]), pendingSales=useMemo(()=>sales.filter(s=>s.status==='PENDING'),[sales]), revenue=useMemo(()=>paidSales.reduce((n,s)=>n+s.amount,0),[paidSales]),pending=useMemo(()=>pendingSales.reduce((n,s)=>n+s.amount,0),[pendingSales]),average=useMemo(()=>paidSales.length?revenue/paidSales.length:0,[paidSales,revenue])
 const soldCount=paidSales.length,activeListings=listings.filter(l=>l.status==='ACTIVE').length,liveAuctions=auctions.filter(a=>a.status==='LIVE').length
 return <main className="mx-auto max-w-7xl px-6 py-14 sm:px-10"><header className="border-b border-ink/15 pb-9"><p className="label-meta">Artist studio</p><h1 className="mt-3 text-5xl sm:text-6xl">Your working archive.</h1><p className="mt-4 max-w-2xl text-ink/60">Catalogue new works, review market activity, and keep every sale and auction in one quiet ledger.</p></header>{(message||error)&&<p className={`mt-6 border p-4 text-sm ${error?'border-oxblood/20 text-oxblood':'border-olive/20 text-olive'}`}>{error||message}</p>}
 <section className="mt-10 grid gap-px border border-ink/10 bg-ink/10 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Paid revenue" value={`INR ${revenue.toLocaleString(undefined,{maximumFractionDigits:2})}`}/><Metric label="Pending sales" value={`INR ${pending.toLocaleString(undefined,{maximumFractionDigits:2})}`}/><Metric label="Completed sales" value={String(soldCount)}/><Metric label="Average sale" value={`INR ${average.toLocaleString(undefined,{maximumFractionDigits:2})}`}/><Metric label="Active listings" value={String(activeListings)}/></section>
 <section className="mt-12"><div className="flex items-end justify-between"><div><p className="label-meta">Catalogue</p><h2 className="mt-2 font-serif text-3xl">Your works</h2></div><span className="text-xs text-ink/40">{works.length} published</span></div>{loading?<p className="py-16 text-sm text-ink/45">Reading your archive…</p>:<div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{works.map(a=><article key={a.id} className="museum-card overflow-hidden"><div className="aspect-[4/3] bg-ivory">{a.imageUrl?<img src={a.imageUrl} alt={a.title} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center font-serif text-3xl text-ink/15">ARTVERSE</div>}</div><div className="p-5"><div className="flex justify-between"><span className="label-meta">{a.category}</span><span className="text-[10px] uppercase tracking-wider text-ink/40">{a.status}</span></div><h3 className="mt-2 font-serif text-2xl">{a.title}</h3><p className="mt-2 text-xs text-ink/45">{a.views} views · {a.currency} {a.price?.toLocaleString()??'No price'}</p><div className="mt-5 grid grid-cols-2 gap-2"><Link to={`/artworks/${a.id}`} className="btn-outline justify-center">View</Link><button onClick={()=>void remove(a.id)} disabled={action===a.id} className="btn-outline justify-center">Remove</button><button onClick={()=>void market(a)} disabled={action===`market-${a.id}`} className="border border-ink/20 px-3 py-3 text-[9px] uppercase tracking-wider">Market</button><button onClick={()=>void auction(a)} disabled={action===`auction-${a.id}`} className="border border-ink/20 px-3 py-3 text-[9px] uppercase tracking-wider">Auction</button></div></div></article>)}</div>}</section>
 <Management title="Private market" label="Listings" empty="No marketplace activity yet.">{listings.map(l=><article key={l.id} className="flex flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="label-meta">{l.status} · {l.currency}</p><p className="mt-1 font-serif text-xl">{l.currency} {l.price.toLocaleString()}</p><p className="text-xs text-ink/40">Listed {new Date(l.createdAt).toLocaleDateString()}</p></div><div className="flex gap-2"><Link to={`/artworks/${l.artworkId}`} className="btn-outline">View work</Link>{l.status==='ACTIVE'&&<button onClick={()=>void cancelListing(l.id)} className="btn-outline">Cancel</button>}</div></article>)}</Management>
 <Management title="Auction rooms" label="Your auctions" empty="No auctions have been created yet.">{auctions.map(a=><article key={a.id} className="flex flex-col gap-4 px-4 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="label-meta">{a.status} · ends {new Date(a.endsAt).toLocaleString()}</p><p className="mt-1 font-serif text-xl">Current offer · {a.currency} {a.currentPrice.toLocaleString()}</p><p className="text-xs text-ink/40">Starting {a.currency} {a.startingPrice.toLocaleString()}</p></div><div className="flex gap-2"><Link to={`/auctions/${a.id}`} className="btn-outline">Open room</Link>{a.status==='LIVE'&&new Date(a.endsAt).getTime()<=Date.now()&&<button onClick={()=>void closeAuction(a.id)} className="btn-outline">Close</button>}{a.status==='ENDED'&&a.winnerId&&<span className="border border-olive/20 px-4 py-2 text-[10px] uppercase tracking-wider text-olive">Winner recorded</span>}</div></article>)}</Management>
 <Management title="Sales ledger" label="Completed & pending" empty="Your sales will appear here.">{sales.map(s=><article key={s.id} className="flex flex-col gap-3 px-4 py-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><p className="label-meta">{s.status}{s.auctionId?' · Auction settlement':''}</p>{s.status==='PAID'&&<span className="text-[10px] uppercase tracking-wider text-olive">Settled</span>}</div><p className="mt-1 font-serif text-xl">{s.currency} {s.amount.toLocaleString()}</p><p className="text-xs text-ink/40">{new Date(s.createdAt).toLocaleString()} {s.buyerId&&<>· Buyer {s.buyerId.slice(0,8)}</>}</p></div><Link to={`/artworks/${s.artworkId}`} className="btn-outline">View work</Link></article>)}</Management>
 <section className="mt-16 border-t border-ink/10 pt-10"><div className="flex items-end justify-between"><div><p className="label-meta">New catalogue record</p><h2 className="mt-2 font-serif text-3xl">Add a work</h2></div><span className="text-xs text-ink/40">All prices in INR</span></div><form onSubmit={submit} className="mt-8 grid gap-7 border-t border-ink/10 pt-8 md:grid-cols-2"><Field label="Title" value={title} setValue={setTitle} required/><Field label="Image URL" value={imageUrl} setValue={setImageUrl}/><Field label="Style" value={style} setValue={setStyle}/><Field label="Medium" value={medium} setValue={setMedium}/><Field label="Year" value={year} setValue={setYear}/><Field label="Price (INR)" value={price} setValue={setPrice}/><label className="text-sm">Category<select value={category} onChange={e=>setCategory(e.target.value)} className="field mt-2"><option>Painting</option><option>Sculpture</option><option>Photography</option><option>Digital</option><option>Printmaking</option><option>Mixed Media</option></select></label><label className="text-sm md:col-span-2">Description<textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 w-full border border-ink/20 bg-transparent p-4 outline-none focus:border-oxblood"/></label><div className="md:col-span-2 flex justify-end border-t border-ink/15 pt-7"><button className="bg-oxblood px-8 py-4 text-sm uppercase tracking-widest text-paper hover:bg-ink">Add to archive</button></div></form></section></main>
}
function Metric({label,value}:{label:string,value:string}){return <div className="bg-paper px-5 py-6"><p className="label-meta">{label}</p><p className="mt-2 font-serif text-2xl">{value}</p></div>}
function Management({title,label,empty,children}:{title:string,label:string,empty:string,children:ReactNode}){return <section className="mt-16 border-t border-ink/10 pt-10"><p className="label-meta">{label}</p><h2 className="mt-2 font-serif text-3xl">{title}</h2><div className="mt-6 divide-y divide-ink/10 border-y border-ink/10">{children||<p className="px-4 py-8 text-sm text-ink/45">{empty}</p>}</div></section>}
function Field({label,value,setValue,required=false}:{label:string,value:string,setValue:(v:string)=>void,required?:boolean}){return <label className="text-sm">{label}<input required={required} value={value} onChange={e=>setValue(e.target.value)} className="field mt-2"/></label>}
