import { FormEvent, useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, extractErrorMessage } from '@/lib/api'
import { createArtwork } from '@/lib/artworks'
import type { Artwork } from '@/types/artwork'

type Page = { content?: Artwork[]; totalElements?: number }

export function StudioPage() {
  const navigate=useNavigate(); const [works,setWorks]=useState<Artwork[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [imageUrl,setImageUrl]=useState(''); const [category,setCategory]=useState('Painting'); const [medium,setMedium]=useState(''); const [style,setStyle]=useState(''); const [year,setYear]=useState(''); const [price,setPrice]=useState('')
  async function load(){try{const r=await api.get<Page>('/artworks/mine',{params:{page:0,size:50}});setWorks(r.data.content??[])}catch(e){setError(extractErrorMessage(e))}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  async function submit(e:FormEvent){e.preventDefault();setMessage('Saving work...');setError('');try{const a=await createArtwork({title,description,imageUrl,category,medium,style,yearCreated:year?Number(year):undefined,price:price?Number(price):undefined,currency:'INR',status:'PUBLISHED'});setWorks(w=>[a,...w]);setTitle('');setDescription('');setImageUrl('');setMedium('');setStyle('');setYear('');setPrice('');setMessage('Work added to your archive.')}catch(e){setError(extractErrorMessage(e));setMessage('')}}
  async function remove(id:string){if(!window.confirm('Remove this work from the archive?'))return;setError('');try{await api.delete(`/artworks/${id}`);setWorks(w=>w.filter(a=>a.id!==id));setMessage('Work removed.')}catch(e){setError(extractErrorMessage(e))}}
  return <main className="mx-auto max-w-7xl px-6 py-14 sm:px-10">
    <header className="border-b border-ink/15 pb-9"><p className="label-meta">Artist studio</p><h1 className="mt-3 text-5xl sm:text-6xl">Your working archive.</h1><p className="mt-4 max-w-2xl text-ink/60">Catalogue new works, review what is published, and prepare pieces for the market.</p></header>
    {(message||error)&&<p className={`mt-6 border p-4 text-sm ${error?'border-oxblood/20 text-oxblood':'border-olive/20 text-olive'}`}>{error||message}</p>}
    <section className="mt-12"><div className="flex items-end justify-between"><div><p className="label-meta">Catalogue</p><h2 className="mt-2 font-serif text-3xl">Your works</h2></div><span className="text-xs text-ink/40">{works.length} published</span></div>{loading?<p className="py-16 text-sm text-ink/45">Reading your archive…</p>:works.length===0?<p className="mt-6 border border-dashed border-ink/20 py-16 text-center text-sm text-ink/45">Your first work will appear here.</p>:<div className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{works.map(a=><article key={a.id} className="museum-card overflow-hidden"><div className="aspect-[4/3] bg-ivory">{a.imageUrl?<img src={a.imageUrl} alt={a.title} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center font-serif text-3xl text-ink/15">ARTVERSE</div>}</div><div className="p-5"><div className="flex justify-between gap-3"><span className="label-meta">{a.category}</span><span className="text-[10px] uppercase tracking-wider text-ink/40">{a.status}</span></div><h3 className="mt-2 font-serif text-2xl">{a.title}</h3><p className="mt-2 text-xs text-ink/45">{a.views} views · {a.currency} {a.price?.toLocaleString()??'No price'}</p><div className="mt-5 flex gap-2"><Link to={`/artworks/${a.id}`} className="btn-outline flex-1 justify-center">View</Link><button onClick={()=>void remove(a.id)} className="px-3 text-[10px] uppercase tracking-wider text-oxblood hover:underline">Remove</button></div></div></article>)}</div>}</section>
    <section className="mt-16 border-t border-ink/10 pt-10"><p className="label-meta">New catalogue record</p><h2 className="mt-2 font-serif text-3xl">Add a work</h2><form onSubmit={submit} className="mt-8 grid gap-7 border-t border-ink/10 pt-8 md:grid-cols-2"><Field label="Title" value={title} setValue={setTitle} required/><Field label="Image URL" value={imageUrl} setValue={setImageUrl}/><Field label="Style" value={style} setValue={setStyle}/><Field label="Medium" value={medium} setValue={setMedium}/><Field label="Year" value={year} setValue={setYear}/><Field label="Price (INR)" value={price} setValue={setPrice}/><label className="text-sm">Category<select value={category} onChange={e=>setCategory(e.target.value)} className="field mt-2"><option>Painting</option><option>Sculpture</option><option>Photography</option><option>Digital</option><option>Printmaking</option><option>Mixed Media</option></select></label><label className="text-sm md:col-span-2">Description<textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)} className="mt-2 w-full border border-ink/20 bg-transparent p-4 outline-none focus:border-oxblood"/></label><div className="md:col-span-2 flex justify-end border-t border-ink/15 pt-7"><button className="bg-oxblood px-8 py-4 text-sm uppercase tracking-widest text-paper hover:bg-ink">Add to archive</button></div></form></section>
  </main>
}
function Field({label,value,setValue,required=false}:{label:string,value:string,setValue:(v:string)=>void,required?:boolean}){return <label className="text-sm">{label}<input required={required} value={value} onChange={e=>setValue(e.target.value)} className="field mt-2"/></label>}
